### ISSUE TITLE
Logo erstellen

### ISSUE THREAD

**Issue by KirstenWesker** [findme-react/management#1]
Aus den Skizzen und Ideen ein fertiges Logo muss in Photoshop entworfen werden

**Comment by KrayZeee** [comment]
erste version des logos ist nun online [klicke hier](https://github.com/findme-react/management/commit/369e26604807d9b0eb5d2265dbfff4cc4e8e4e2c) sagt mir was euch nicht passt, wird dann angepasst

**Comment by KirstenWesker** [comment]
Bitte einmal die Version aus er Skizze mit den Zacken an den "Enden" der Unendlichkeitsschleife ausprobieren, damit man sehen kann was besser aussieht. Den Hintergrund eventuell transparent.

**Comment by KirstenWesker** [comment]
Bitte die überarbeitete Version hochladen :D
